# Generated by Django 4.0.5 on 2022-06-19 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100, verbose_name='Устройство')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('open', 'Открыт'), ('close', 'Закрыт')], default='open', max_length=5, verbose_name='Статус заказа')),
                ('order_number', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='backend.order')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
