# Generated by Django 4.0.5 on 2022-08-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'order'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='creation_date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='creation_date',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sum',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(),
        ),
    ]
