# Generated by Django 4.0.5 on 2022-08-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
