# Generated by Django 4.0.5 on 2022-08-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='summ',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('work', 'Обслуживается'), ('done', 'Готов'), ('close', 'Закрыт')], default='open', max_length=5, verbose_name='Статус заказа'),
        ),
    ]
