# Generated by Django 4.0.5 on 2022-08-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_cash_user_alter_comment_order_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.TextField(default=1, verbose_name='Выполненная работа'),
            preserve_default=False,
        ),
    ]
