# Generated by Django 4.0.5 on 2022-08-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_order_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Выполненная работа'),
        ),
    ]
