# Generated by Django 4.0.5 on 2022-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Адрес клиента'),
        ),
    ]
